baseURL = 'https://davidevvi.github.io/'
languageCode = 'en-us'
title = 'A Jester'
theme = "shibui"

[params]
  author = "Davide Vallenzasca"
  email = "darvide1998@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
